<?php
/**
 * FontFace
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.14.0.20201015.001
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FirstData\FirstApi\Client\Model;
use \FirstData\FirstApi\Client\ObjectSerializer;

/**
 * FontFace Class Doc Comment
 *
 * @category Class
 * @description Font face property.
 * @package  FirstData\FirstApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FontFace
{
    /**
     * Possible values of this enum
     */
    const ARIAL = 'arial';
    const COURIER_NEW = 'courier new';
    const TIMES_NEW_ROMAN = 'times new roman';
    const TREBUCHET_MS = 'trebuchet ms';
    const VERDANA = 'verdana';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ARIAL,
            self::COURIER_NEW,
            self::TIMES_NEW_ROMAN,
            self::TREBUCHET_MS,
            self::VERDANA,
        ];
    }
}


