<?php
/**
 * TransactionType
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Gateway API Specification
 *
 * Payment Gateway API for payment processing.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace FirstData\FirstApi\Client\Model;
use \FirstData\FirstApi\Client\ObjectSerializer;

/**
 * TransactionType Class Doc Comment
 *
 * @category Class
 * @description Type of transaction to perform. This includes SALE, PREAUTH, CREDIT, FORCED_TICKET.
 * @package  FirstData\FirstApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionType
{
    /**
     * Possible values of this enum
     */
    const SALE = 'SALE';
    const PREAUTH = 'PREAUTH';
    const CREDIT = 'CREDIT';
    const FORCED_TICKET = 'FORCED_TICKET';
    const VOID = 'VOID';
    const _RETURN = 'RETURN';
    const POSTAUTH = 'POSTAUTH';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SALE,
            self::PREAUTH,
            self::CREDIT,
            self::FORCED_TICKET,
            self::VOID,
            self::_RETURN,
            self::POSTAUTH,
        ];
    }
}


