<?php
/**
 * AirlineTest
 *
 * PHP version 7
 *
 * @category Class
 * @package  FirstData\ApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * First Data REST Payment API Specification
 *
 * First Data REST API for payment features for 6.2.0 release
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FirstData\ApiClient;

/**
 * AirlineTest Class Doc Comment
 *
 * @category    Class
 * @description Additional data specific to the airline industry
 * @package     FirstData\ApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AirlineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Airline"
     */
    public function testAirline()
    {
    }

    /**
     * Test attribute "passengerName"
     */
    public function testPropertyPassengerName()
    {
    }

    /**
     * Test attribute "ticketNumber"
     */
    public function testPropertyTicketNumber()
    {
    }

    /**
     * Test attribute "issuingCarrier"
     */
    public function testPropertyIssuingCarrier()
    {
    }

    /**
     * Test attribute "carrierName"
     */
    public function testPropertyCarrierName()
    {
    }

    /**
     * Test attribute "travelAgencyIataCode"
     */
    public function testPropertyTravelAgencyIataCode()
    {
    }

    /**
     * Test attribute "travelAgencyName"
     */
    public function testPropertyTravelAgencyName()
    {
    }

    /**
     * Test attribute "airlinePlanNumber"
     */
    public function testPropertyAirlinePlanNumber()
    {
    }

    /**
     * Test attribute "airlineInvoiceNumber"
     */
    public function testPropertyAirlineInvoiceNumber()
    {
    }

    /**
     * Test attribute "reservationSystem"
     */
    public function testPropertyReservationSystem()
    {
    }

    /**
     * Test attribute "restricted"
     */
    public function testPropertyRestricted()
    {
    }

    /**
     * Test attribute "travelRoute"
     */
    public function testPropertyTravelRoute()
    {
    }

    /**
     * Test attribute "relatedTicketNumber"
     */
    public function testPropertyRelatedTicketNumber()
    {
    }

    /**
     * Test attribute "ancillaryServiceCategory"
     */
    public function testPropertyAncillaryServiceCategory()
    {
    }

    /**
     * Test attribute "ticketPurchase"
     */
    public function testPropertyTicketPurchase()
    {
    }
}
