<?php
/**
 * ApplePayHeaderTest
 *
 * PHP version 7
 *
 * @category Class
 * @package  FirstData\ApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * First Data REST Payment API Specification
 *
 * First Data REST API for payment features for 6.2.0 release
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FirstData\ApiClient;

/**
 * ApplePayHeaderTest Class Doc Comment
 *
 * @category    Class
 * @description Additional version-dependent information used to decrypt and verify the payment
 * @package     FirstData\ApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplePayHeaderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApplePayHeader"
     */
    public function testApplePayHeader()
    {
    }

    /**
     * Test attribute "applicationDataHash"
     */
    public function testPropertyApplicationDataHash()
    {
    }

    /**
     * Test attribute "ephemeralPublicKey"
     */
    public function testPropertyEphemeralPublicKey()
    {
    }

    /**
     * Test attribute "publicKeyHash"
     */
    public function testPropertyPublicKeyHash()
    {
    }

    /**
     * Test attribute "transactionId"
     */
    public function testPropertyTransactionId()
    {
    }
}
