<?php
/**
 * LodgingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Gateway API Specification
 *
 * Payment Gateway API for payment processing.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FirstData\FirstApi\Client;

/**
 * LodgingTest Class Doc Comment
 *
 * @category    Class */
// * @description Lodging
/**
 * @package     FirstData\FirstApi\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LodgingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Lodging"
     */
    public function testLodging()
    {
    }

    /**
     * Test attribute "arrivalDate"
     */
    public function testPropertyArrivalDate()
    {
    }

    /**
     * Test attribute "departureDate"
     */
    public function testPropertyDepartureDate()
    {
    }

    /**
     * Test attribute "folioNumber"
     */
    public function testPropertyFolioNumber()
    {
    }

    /**
     * Test attribute "extraCharges"
     */
    public function testPropertyExtraCharges()
    {
    }

    /**
     * Test attribute "noShowIndicator"
     */
    public function testPropertyNoShowIndicator()
    {
    }
}
