<?php
/**
 * PaymentSchedulesRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Gateway API Specification
 *
 * Payment Gateway API for payment processing.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FirstData\FirstApi\Client;

/**
 * PaymentSchedulesRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description Request to create a gateway scheduler.
/**
 * @package     FirstData\FirstApi\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentSchedulesRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentSchedulesRequest"
     */
    public function testPaymentSchedulesRequest()
    {
    }

    /**
     * Test attribute "storeId"
     */
    public function testPropertyStoreId()
    {
    }

    /**
     * Test attribute "referenceOrderId"
     */
    public function testPropertyReferenceOrderId()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "numberOfPayments"
     */
    public function testPropertyNumberOfPayments()
    {
    }

    /**
     * Test attribute "maximumFailures"
     */
    public function testPropertyMaximumFailures()
    {
    }

    /**
     * Test attribute "invoiceNumber"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "poNumber"
     */
    public function testPropertyPoNumber()
    {
    }

    /**
     * Test attribute "transactionOrigin"
     */
    public function testPropertyTransactionOrigin()
    {
    }

    /**
     * Test attribute "dynamicMerchantName"
     */
    public function testPropertyDynamicMerchantName()
    {
    }

    /**
     * Test attribute "frequency"
     */
    public function testPropertyFrequency()
    {
    }

    /**
     * Test attribute "paymentMethod"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "clientLocale"
     */
    public function testPropertyClientLocale()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }
}
