<?php
/**
 * PaymentSchedulesResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Gateway API Specification
 *
 * Payment Gateway API for payment processing.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FirstData\FirstApi\Client;

/**
 * PaymentSchedulesResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Response from the gateway scheduler creation call.
/**
 * @package     FirstData\FirstApi\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentSchedulesResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentSchedulesResponse"
     */
    public function testPaymentSchedulesResponse()
    {
    }

    /**
     * Test attribute "clientRequestId"
     */
    public function testPropertyClientRequestId()
    {
    }

    /**
     * Test attribute "apiTraceId"
     */
    public function testPropertyApiTraceId()
    {
    }

    /**
     * Test attribute "transactionStatus"
     */
    public function testPropertyTransactionStatus()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }
}
