<?php
/**
 * PrimaryTransactionTest
 *
 * PHP version 7
 *
 * @category Class
 * @package  FirstData\ApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * First Data REST Payment API Specification
 *
 * First Data REST API for payment features for 6.2.0 release
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FirstData\ApiClient;

/**
 * PrimaryTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Model for primary financial transactions
 * @package     FirstData\ApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PrimaryTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PrimaryTransaction"
     */
    public function testPrimaryTransaction()
    {
    }

    /**
     * Test attribute "transactionType"
     */
    public function testPropertyTransactionType()
    {
    }

    /**
     * Test attribute "storeId"
     */
    public function testPropertyStoreId()
    {
    }

    /**
     * Test attribute "clientTransactionId"
     */
    public function testPropertyClientTransactionId()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "paymentMethod"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "basketItems"
     */
    public function testPropertyBasketItems()
    {
    }

    /**
     * Test attribute "splitShipment"
     */
    public function testPropertySplitShipment()
    {
    }

    /**
     * Test attribute "transactionOrigin"
     */
    public function testPropertyTransactionOrigin()
    {
    }

    /**
     * Test attribute "additionalDetails"
     */
    public function testPropertyAdditionalDetails()
    {
    }

    /**
     * Test attribute "industrySpecificExtensions"
     */
    public function testPropertyIndustrySpecificExtensions()
    {
    }
}
