<?php
/**
 * TransactionResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Gateway API Specification
 *
 * Payment Gateway API for payment processing.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FirstData\FirstApi\Client;

/**
 * TransactionResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description This is the common object for primary and secondary payment request responses
/**
 * @package     FirstData\FirstApi\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransactionResponse"
     */
    public function testTransactionResponse()
    {
    }

    /**
     * Test attribute "responseType"
     */
    public function testPropertyResponseType()
    {
    }

    /**
     * Test attribute "clientRequestId"
     */
    public function testPropertyClientRequestId()
    {
    }

    /**
     * Test attribute "apiTraceId"
     */
    public function testPropertyApiTraceId()
    {
    }

    /**
     * Test attribute "ipgTransactionId"
     */
    public function testPropertyIpgTransactionId()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "transactionType"
     */
    public function testPropertyTransactionType()
    {
    }

    /**
     * Test attribute "authorizationCode"
     */
    public function testPropertyAuthorizationCode()
    {
    }

    /**
     * Test attribute "avsResponse"
     */
    public function testPropertyAvsResponse()
    {
    }

    /**
     * Test attribute "securityCodeResponse"
     */
    public function testPropertySecurityCodeResponse()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "terminalId"
     */
    public function testPropertyTerminalId()
    {
    }

    /**
     * Test attribute "clientTransactionId"
     */
    public function testPropertyClientTransactionId()
    {
    }

    /**
     * Test attribute "transactionTime"
     */
    public function testPropertyTransactionTime()
    {
    }

    /**
     * Test attribute "approvedAmount"
     */
    public function testPropertyApprovedAmount()
    {
    }

    /**
     * Test attribute "transactionStatus"
     */
    public function testPropertyTransactionStatus()
    {
    }

    /**
     * Test attribute "transactionState"
     */
    public function testPropertyTransactionState()
    {
    }

    /**
     * Test attribute "authenticationRedirect"
     */
    public function testPropertyAuthenticationRedirect()
    {
    }

    /**
     * Test attribute "schemeTransactionId"
     */
    public function testPropertySchemeTransactionId()
    {
    }

    /**
     * Test attribute "processor"
     */
    public function testPropertyProcessor()
    {
    }
}
