<?php
/**
 * TransactionResponseAuthenticationRedirectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Gateway API Specification
 *
 * Payment Gateway API for payment processing.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FirstData\FirstApi\Client;

/**
 * TransactionResponseAuthenticationRedirectTest Class Doc Comment
 *
 * @category    Class */
// * @description TransactionResponseAuthenticationRedirect
/**
 * @package     FirstData\FirstApi\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionResponseAuthenticationRedirectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransactionResponseAuthenticationRedirect"
     */
    public function testTransactionResponseAuthenticationRedirect()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "targetUrl"
     */
    public function testPropertyTargetUrl()
    {
    }

    /**
     * Test attribute "params"
     */
    public function testPropertyParams()
    {
    }
}
